### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by nanoarmando** [Rogach/cacheftpfs#1]
Hi, i have the same problem with curlftpfs, can you tellme how to use this script?

**Comment by Rogach** [comment]
Run the following command:

```
cacheftpfs.py --mountpoint <mount point> --host <machine address> --user <ftp username> --pass <ftp password>
```

By default it runs in foreground and will terminate the connection once you close the terminal, but you can send it to background by appending `&` to command.
